#!/bin/bash

source "$(dirname "$0")/common.bash"

declare -r new_version="${1}"

if [ -z "${new_version}" ] ; then
    echo "Please supply a new version."
    exit 2
fi

declare starting_version
starting_version=$(get_current_parent_version)

# Validation also brings down a lot of artifacts, which will
# speed up subsequent operations.
echo "Starting with parent version ${starting_version}"

echo -n "Validating current project state..."

if ! run_maven -q validate ; then
    exit 1
fi

echo "done."

# We can use a simple parent version if skipResolution is true.
if ! run_maven org.codehaus.mojo:versions-maven-plugin:2.14.1:update-parent -DskipResolution=true "-DparentVersion=${new_version}" ; then
    echo "Project versions could not updated."
    exit 1
fi

echo "Checking for traces of previous versions; some could be benign."

find . -name pom.xml -print0 | xargs -0 grep -l -F "<version>${starting_version}</version>"

echo "...done with check."
